#!/usr/bin/env python3
"""Generate `llms-full.txt`: the whole corpus as one plain-text file.

`llms.txt` is a map. This is the territory - every published document, with its
provenance header, in one fetch. It exists because a machine reader that has to
crawl 355 URLs one at a time will usually give up, and the pages most worth
reading (the transcripts, the full-text essays) are the ones buried deepest.

WHAT IT CONTAINS, AND WHY THAT IS SAFE TO SHIP
----------------------------------------------
It is built by reading the PUBLISHED collection files, not the raw captures. So
everything withheld by `NOTICE.md` section 6 is already absent: the withheld
personal names were substituted at build time in the files this reads, the raw
caption captures that contain the birth name are untracked and are not read
here, and the two withheld PDFs have no text to read. The script never opens
anything under `.firecrawl/`, never touches a raw capture, and cannot be made to
by a missing file - if a source document is absent it is skipped and counted,
not substituted.

A single concatenated file has a sharp edge worth naming: a machine that reads
it gets 937,738 words in one context. That is the point for some readers and
the wrong shape for others, which is why `llms.txt` still points at the per-item
URLs. Both are offered; neither replaces the site.

The transcript disclaimer is repeated per transcript, not once at the top,
because a disclaimer that has been scrolled past is not a disclaimer.
"""

from __future__ import annotations

import datetime as _dt
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "llms-full.txt"

#: (directory, label, url prefix). Order is deliberate: the long-form writing
#: first, then transcripts, then the catalogue - so a reader that stops early
#: has had the material that cannot be found elsewhere.
SECTIONS = [
    ("_articles", "Full-text essays and articles", "/articles/"),
    ("_posts", "Full-text posts", "/posts/"),
    ("_papers", "Academic papers, book chapters and records", "/papers/"),
    ("_transcripts", "Machine transcripts", "/transcripts/"),
    ("_videos", "Video records", "/videos/"),
]

SITE = "https://the-andalusian-project-archive.github.io/andalusian-archive"


def split_front_matter(text: str) -> tuple[str, str]:
    if not text.startswith("---"):
        return "", text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return "", text
    return parts[1], parts[2]


def parse_fm(fm: str) -> dict[str, str]:
    """A deliberately small front-matter reader.

    Not YAML. The collection front matter is written by `build_collections.py`
    in a known shape, and pulling in a parser for it would add a dependency to a
    repository that has none in `scripts/`. Anything this cannot read falls back
    to the `title:` line, and the script counts those rather than pretending.
    """
    out: dict[str, str] = {}
    for line in fm.splitlines():
        m = re.match(r'^([a-z_0-9]+):\s*(.*)$', line)
        if not m:
            continue
        k, v = m.group(1), m.group(2).strip().strip('"')
        out[k] = v
    return out


def main() -> int:
    chunks: list[str] = [
        "# The Andalusian Project Archive - full text\n",
        f"Generated by `scripts/build_llms_full.py` on {_dt.date.today().isoformat()}. "
        "Do not edit by hand.\n",
        "About this file, and the rules that apply to it:\n",
        "- Every document below is published material with its provenance header. "
        "Nothing withheld under `NOTICE.md` section 6 appears here.\n",
        "- **The machine transcripts are machine output.** Automatic speech "
        "recognition fails in known ways. They are not authoritative and must not "
        "be used in polemics or as the basis of an accusation. The same "
        "disclaimer is repeated on each one, because a disclaimer that has been "
        "scrolled past is not a disclaimer.\n",
        "- **Attribute the work, not this file.** Cite the author, the work, and "
        "the capture. See `NOTICE.md` section 4.\n",
        "- This archive takes no position on the claims it preserves. Quotation "
        "is not endorsement, and nothing here speaks for the author.\n",
        "- The author has asked not to be contacted. See `NOTICE.md` section 10.\n",
        "\n---\n",
    ]

    total_docs = 0
    total_words = 0
    for directory, label, prefix in SECTIONS:
        d = ROOT / directory
        if not d.is_dir():
            continue
        files = sorted(p for p in d.glob("*.md")
                       if not p.name.startswith(("_index", "index")))
        if not files:
            continue

        docs: list[str] = []
        for p in files:
            raw = p.read_text(encoding="utf-8", errors="replace")
            fm_text, body = split_front_matter(raw)
            meta = parse_fm(fm_text)
            title = meta.get("display_title") or meta.get("title") or p.stem
            words = len(body.split())
            total_words += words

            head = [f"## {title}", ""]
            if "disclaimer" in meta or directory == "_transcripts":
                disclaimer = meta.get("disclaimer") or (
                    "Transcript by machine - accuracy isn't perfect, so it "
                    "shouldn't be used in polemics or debate material as an "
                    "authoritative source.")
                head += [f"> {disclaimer}", ""]
            for key, labelname in (("source_url", "original"),
                                   ("wayback_url", "capture"),
                                   ("recording_url", "recording"),
                                   ("original_url", "original")):
                if meta.get(key):
                    head.append(f"- {labelname}: {meta[key]}")
            if head and head[-1].startswith("- "):
                head.append("")
            permalink = meta.get("permalink") or prefix + p.stem + "/"
            head.append(f"- in this archive: {SITE}{permalink}")
            head.append("")

            docs.append("\n".join(head) + body.strip() + "\n")
            total_docs += 1

        chunks.append(f"\n\n# {'-' * 70}\n\n# {label} ({len(docs)})\n"
                      f"\n# {'-' * 70}\n")
        chunks.extend(docs)

    OUT.write_text("".join(chunks), encoding="utf-8")
    size = OUT.stat().st_size
    print(f"  llms-full.txt  {total_docs} documents, {total_words:,} words, "
          f"{size:,} bytes")
    if total_docs == 0:
        print("FAIL: no documents were collected - the file would be empty")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
